[tool.poetry]
name = "atari_10k"
version = 1.0
description = "Atari 10k dataset

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.files]
include = ["*.py", "README.md", "LICENSE", "manuals/*"]